/*Pokemon Type Database*/
pokemon(electric,'Galvantula').
pokemon(steel,'Scizor').
pokemon(steel,'Steelix').
pokemon(phsyic,'Mewtwo').
pokemon(water,'Greninja').
pokemon(water,'Tododile').
pokemon(electric,'Pikachu').
pokemon(fairy,'Jiglypuff').
pokemon(fighting,'Lucario').
pokemon(normal,'Eevee').
pokemon(fairy,'Sylveon').
pokemon(dark,'Umbreon').
pokemon(physcic,'Espeon').
pokemon(fire,'Chandelure').
pokemon(fire,'Charizard').
pokemon(fire,'Volcarona').
pokemon(normal,'Arceus').
pokemon(ghost,'Gengar').
pokemon(ghost,'Spiritomb').
pokemon(water,'Feebas').
